# Generated by Django 5.0 on 2024-03-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_gender_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("A", "admin"), ("M", "manager"), ("U", "auth_user")],
                default="U",
                max_length=1,
                verbose_name="role",
            ),
        ),
    ]
