# Generated by Django 5.0 on 2024-04-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="address",
            new_name="address_building",
        ),
        migrations.AddField(
            model_name="user",
            name="address_flat",
            field=models.CharField(blank=True, max_length=255, verbose_name="delivery address"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_street",
            field=models.CharField(blank=True, max_length=255, verbose_name="delivery address"),
        ),
        migrations.AddField(
            model_name="user",
            name="address_town",
            field=models.CharField(blank=True, max_length=255, verbose_name="delivery address"),
        ),
        migrations.AddField(
            model_name="user",
            name="nova_poshta_post_office",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="nova_poshta post office"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nova_poshta_town",
            field=models.CharField(blank=True, max_length=100, verbose_name="nova_poshta town"),
        ),
        migrations.AddField(
            model_name="user",
            name="ukr_poshta_post_office",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="nova_poshta post office"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ukr_poshta_town",
            field=models.CharField(blank=True, max_length=100, verbose_name="nova_poshta town"),
        ),
    ]
