version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: AlexUA
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
