# fly.toml app configuration file generated for alex-online-store on 2023-07-29T12:49:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alex-online-store"
primary_region = "mad"

[mounts]
  source="volume_shop_mad"
  destination="/code/shop"


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/code/shop/static"
  url_prefix = "/static/"
