# fly.toml app configuration file generated for alex-online-store on 2023-07-29T12:49:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alex-online-store"
primary_region = "mad"


[env]
  PORT = "8000"
  DJANGO_SECRET_KEY = "django-insecure-^zu#y#&xp6osjy7v)yl8pe)_%*2e*7@bphh282jn#v6ktd#sw0"
  POSTGRES_DB = "postgres"
  POSTGRES_PASSWORD =    "CO7DKd4bffFloXk"
  POSTGRES_USER = "postgres"
  DB_HOST =    "alexuadb.internal"
  Proxy_port =  "5432"
  PORT_DB =  "5433"
  DATABASE_URL = "postgres://postgres:CO7DKd4bffFloXk@alexuadb.internal:5432"
  DEBUG = "False"


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
