# Generated by Django 4.2.3 on 2023-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_rating_customer_alter_rating_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="delivery rating",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="foto_quality",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="foto quality rating",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="global_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="global rating",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quality",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="quality rating",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="global_value",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="global rating",
            ),
        ),
    ]
