# Generated by Django 4.2.3 on 2023-08-11 14:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_product_delivery_product_foto_quality_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name settimgs"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="category description"),
                ),
                ("value", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
