# Generated by Django 4.2.3 on 2023-08-17 17:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="product name")),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="product name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="product slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="product description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banner/",
                        verbose_name="banner image",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="update"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="category/",
                verbose_name="product image",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="category/",
                verbose_name="product image small",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="product image small",
            ),
        ),
    ]
