# Generated by Django 4.2.3 on 2023-08-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_banner_category_image_category_image_small_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="image",
            new_name="img",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="name",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="slug",
        ),
        migrations.AddField(
            model_name="banner",
            name="link",
            field=models.URLField(default="/catalog", verbose_name="link"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=200, verbose_name="product name"),
        ),
    ]
