# Generated by Django 4.2.3 on 2023-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_rename_image_banner_img_remove_banner_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="link",
            field=models.CharField(default="/catalog", verbose_name="link"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
    ]
