# Generated by Django 4.2.3 on 2023-08-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_category_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category",
                to="shop.category",
            ),
        ),
    ]
