# Generated by Django 4.2.3 on 2023-08-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_category_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-category__name", "name"]},
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/category/",
                verbose_name="category image",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/category/",
                verbose_name="category icon image small",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/product/",
                verbose_name="product image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/product/",
                verbose_name="product image small",
            ),
        ),
    ]
