# Generated by Django 4.2.3 on 2023-08-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_alter_category_options_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="product type"
            ),
        ),
    ]
