# Generated by Django 4.2.3 on 2023-09-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_product_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_small",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_small",
        ),
        migrations.AddField(
            model_name="banner",
            name="mobileImg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/banners/",
                verbose_name="banner for mobile",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/categories/",
                verbose_name="category image",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="img_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/categories/",
                verbose_name="category icon image small",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/products/",
                verbose_name="product image",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="img_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="foto/products/",
                verbose_name="product image small",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="global_value",
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="global rating",
            ),
        ),
    ]
