# Generated by Django 4.2.3 on 2023-09-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_remove_category_image_remove_category_image_small_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="global_rating",
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="global rating",
            ),
        ),
    ]
