# Generated by Django 4.2.3 on 2023-09-04 14:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_alter_product_global_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="slug",
            field=models.SlugField(
                default=uuid.UUID("1c3c9753-e845-4c0a-9a00-1b3a08e06d9f"),
                unique=True,
                verbose_name="product slug",
            ),
        ),
    ]
