# Generated by Django 4.2.3 on 2023-09-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_banner_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="product slug"),
        ),
    ]
