# Generated by Django 4.2.3 on 2023-09-09 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0017_alter_banner_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="category description"),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ua",
            field=models.TextField(blank=True, null=True, verbose_name="category description"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="category name"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ua",
            field=models.CharField(max_length=100, null=True, verbose_name="category name"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="product description"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ua",
            field=models.TextField(blank=True, null=True, verbose_name="product description"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="product name"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ua",
            field=models.CharField(max_length=200, null=True, verbose_name="product name"),
        ),
        migrations.AddField(
            model_name="product",
            name="type_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="product type"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type_ua",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="product type"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
