# Generated by Django 4.2.3 on 2023-09-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_category_description_en_category_description_ua_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="banner",
            name="description_ua",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="banner",
            name="title_ua",
            field=models.CharField(max_length=200, null=True, verbose_name="title"),
        ),
    ]
