# Generated by Django 4.2.3 on 2023-09-13 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0023_product_wishlist_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="wishlist_users",
            new_name="wishlist",
        ),
    ]
