# Generated by Django 4.2.3 on 2023-09-13 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0024_rename_wishlist_users_product_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="wishlist",
            field=models.ManyToManyField(related_name="wishlist", to=settings.AUTH_USER_MODEL),
        ),
    ]
