# Generated by Django 4.2.3 on 2023-10-13 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0027_product_shop_produc_created_3b0d54_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="quantity product"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(check=models.Q(("price__gt", 0)), name="valid_price"),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shop.product"),
        ),
        migrations.AddField(
            model_name="basketitem",
            name="registered_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="basket",
            field=models.ManyToManyField(through="shop.BasketItem", to=settings.AUTH_USER_MODEL),
        ),
    ]
