# Generated by Django 4.2.3 on 2023-10-13 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0029_alter_basketitem_registered_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prod_in_basket",
                to="shop.product",
            ),
        ),
    ]
