# Generated by Django 4.2.3 on 2023-10-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0030_alter_basketitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="category description"),
        ),
        migrations.AddField(
            model_name="settings",
            name="description_ua",
            field=models.TextField(blank=True, null=True, verbose_name="category description"),
        ),
        migrations.AddField(
            model_name="settings",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name settimgs"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="name_ua",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name settimgs"
            ),
        ),
    ]
