# Generated by Django 4.2.3 on 2023-11-17 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0033_banner_img_en_banner_img_ua_banner_mobileimg_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="img_en",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="img_ua",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="mobileImg_en",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="mobileImg_ua",
        ),
    ]
