# Generated by Django 4.2.3 on 2023-11-23 21:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0035_banner_img_en_banner_img_ua_banner_mobileimg_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="foto_quality",
            new_name="photo_match",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="delivery",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="description_quality",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="global_value",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="value",
        ),
        migrations.AddField(
            model_name="product",
            name="img1",
            field=models.ImageField(
                blank=True, null=True, upload_to="foto/products/", verbose_name="product image 1"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="img2",
            field=models.ImageField(
                blank=True, null=True, upload_to="foto/products/", verbose_name="product image 2"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="img3",
            field=models.ImageField(
                blank=True, null=True, upload_to="foto/products/", verbose_name="product image 3"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="description_match",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="description match",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="price",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="price",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="rate_by_stars",
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="rate by stars",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="wishlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="description_ua",
            field=models.TextField(blank=True, null=True, verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="name_ua",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="title"),
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="question")),
                ("answer", models.TextField(verbose_name="answer")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
