# Generated by Django 4.2.3 on 2023-11-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0036_rename_foto_quality_rating_photo_match_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="delivery",
        ),
        migrations.RemoveField(
            model_name="product",
            name="foto_quality",
        ),
        migrations.AddField(
            model_name="product",
            name="description_match",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="description_match",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="photo_match",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="photo_match",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_price",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
                verbose_name="price",
            ),
        ),
    ]
