# Generated by Django 4.2.3 on 2023-11-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0038_product__1_product__2_product__3_product__4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(null=True, verbose_name="answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_ua",
            field=models.TextField(null=True, verbose_name="answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=200, null=True, verbose_name="question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_ua",
            field=models.CharField(max_length=200, null=True, verbose_name="question"),
        ),
    ]
