# Generated by Django 4.2.3 on 2023-11-28 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0039_faq_answer_en_faq_answer_ua_faq_question_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="customer",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="created_at",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="body",
            new_name="text",
        ),
    ]
