# Generated by Django 5.0 on 2024-01-23 09:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0043_alter_product_description_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="another_person_firstName",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="another person first name"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="another_person_lastName",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="another person last name"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="another_person_tel",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="building",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                blank=True,
                choices=[("COURIER", "courier"), ("POST_OFFICE", "post_office")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("SELF", "self"), ("NOVA", "nova"), ("UKR", "ukr")],
                default="SELF",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="order",
            name="flat",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_another_person",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_gift",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_not_recall",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="order",
            name="post_office",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tel",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="town",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
