# Generated by Django 5.0 on 2024-01-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0045_alter_basketitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="id2",
            field=models.IntegerField(auto_created=True, default=0, editable=False),
        ),
    ]
