# Generated by Django 5.0 on 2024-01-23 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0046_order_id2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
