# Generated by Django 5.0 on 2024-01-23 10:45

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0047_remove_orderitem_order_remove_orderitem_product_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW_ORDER", "new order"),
                            ("READY", "ready"),
                            ("ON_ITS_WAY", "on its way"),
                            ("DELIVERED", "delivered"),
                        ],
                        default="NEW_ORDER",
                        max_length=11,
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="create order"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="update order")),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="total amount order",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="last name"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("SELF", "self"), ("NOVA", "nova"), ("UKR", "ukr")],
                        default="SELF",
                        max_length=5,
                    ),
                ),
                (
                    "delivery_option",
                    models.CharField(
                        blank=True,
                        choices=[("COURIER", "courier"), ("POST_OFFICE", "post_office")],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("town", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                ("building", models.CharField(blank=True, max_length=50, null=True)),
                ("flat", models.CharField(blank=True, max_length=50, null=True)),
                ("post_office", models.CharField(blank=True, max_length=50, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("is_not_recall", models.BooleanField(default=False)),
                ("is_another_person", models.BooleanField(default=False)),
                ("is_gift", models.BooleanField(default=False)),
                ("is_comment", models.BooleanField(default=False)),
                (
                    "another_person_tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "another_person_firstName",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="another person first name",
                    ),
                ),
                (
                    "another_person_lastName",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="another person last name",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="quantity product"),
                ),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shop.order"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(through="shop.OrderItem", to="shop.product"),
        ),
    ]
