# Generated by Django 5.0 on 2024-01-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0048_order_orderitem_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
