# Generated by Django 5.0 on 2024-01-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0049_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
