# Generated by Django 5.0 on 2024-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0050_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                blank=True,
                choices=[("courier", "courier"), ("post_office", "post_office")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("self", "self"), ("nova", "nova"), ("ukr", "ukr")],
                default="SELF",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new_order", "new order"),
                    ("ready", "ready"),
                    ("on_its_way", "on its way"),
                    ("delivered", "delivered"),
                ],
                default="NEW_ORDER",
                max_length=11,
            ),
        ),
    ]
