# Generated by Django 5.0 on 2024-04-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0053_basketitem_is_secret_present_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="foto/products/", verbose_name="product image"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="discount"
            ),
        ),
    ]
