# Generated by Django 5.0 on 2024-04-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0054_orderitem_img_orderitem_name_orderitem_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("staffing", "staffing"),
                    ("sending", "sending"),
                    ("returning", "returning"),
                    ("completing", "completing"),
                ],
                default="staffing",
                max_length=11,
            ),
        ),
    ]
