# Generated by Django 5.0 on 2024-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0056_rename_rate_by_stars_review_global_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="description_match",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=0,
                verbose_name="description match",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="global_rate",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=0,
                verbose_name="global_rating",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="photo_match",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=0,
                verbose_name="foto quality rating",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="price",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=0,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="quality",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=0,
                verbose_name="quality rating",
            ),
        ),
    ]
